version: "3.9"

services:

  db:
    image: postgres:16

    container_name: enterprise_postgres

    restart: always

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Enterprise@123
      POSTGRES_DB: enterprise_ai

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: .

    container_name: enterprise_backend

    depends_on:
      - db

    env_file:
      - .env

    ports:
      - "8000:8000"

    volumes:
      - .:/app

    command: >
      uvicorn app.main:app
      --host 0.0.0.0
      --port 8000
      --reload

volumes:
  postgres_data: